# Generated by Django 3.2.7 on 2021-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211006_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
