# Generated by Django 3.2.7 on 2021-10-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbid', models.IntegerField()),
                ('tmdbid', models.IntegerField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.movie')),
            ],
        ),
    ]
