# Generated by Django 3.2.7 on 2021-10-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='links',
        ),
    ]
