# Generated by Django 3.2.7 on 2021-10-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
