# Generated by Django 3.2.7 on 2021-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('genres', models.CharField(max_length=30)),
                ('imdb_id', models.IntegerField()),
                ('tmdb_id', models.IntegerField()),
                ('Image_url', models.URLField()),
                ('text', models.TextField(max_length=400)),
            ],
        ),
    ]
