# Generated by Django 3.2.7 on 2021-10-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211019_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
