# Generated by Django 3.2.7 on 2021-10-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
