# Generated by Django 3.2.7 on 2021-10-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='add_movie_to_list',
            field=models.ManyToManyField(related_name='add_movie_to_list', to='accounts.User'),
        ),
    ]
