# Generated by Django 3.2.7 on 2021-10-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211023_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='user',
            new_name='user_id',
        ),
    ]
