# Generated by Django 3.2.7 on 2021-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_user_fav_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favourite',
            field=models.ManyToManyField(to='accounts.User'),
        ),
        migrations.DeleteModel(
            name='fav',
        ),
    ]
