# Generated by Django 3.2.7 on 2021-10-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_movie_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='favourite',
            new_name='favourites',
        ),
    ]
