# Generated by Django 3.2.7 on 2021-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_favourite_movie_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='accounts.User'),
        ),
    ]
