# Generated by Django 3.2.7 on 2021-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_movie_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='accounts.User'),
        ),
    ]
