# Generated by Django 3.2.7 on 2021-10-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_movie_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
