# Generated by Django 3.2.7 on 2021-10-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20211024_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
    ]
