# Generated by Django 3.2.7 on 2021-10-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
    ]
