# Generated by Django 3.2.7 on 2021-10-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
