# Generated by Django 3.2.7 on 2021-11-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_fav_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
